# 1/2 Create build image
FROM node:8 AS build

RUN mkdir -p /opt/geoplatform-web
WORKDIR /opt/geoplatform-web

COPY package.json yarn.lock ./
RUN yarn --production

# 2/2 Create production image
FROM node:8-slim
ARG SOURCE_COMMIT=unknown

RUN apt-get update -qq && \
    apt-get install -qq -y gdal-bin

RUN mkdir -p /opt/geoplatform-web
WORKDIR /opt/geoplatform-web

COPY --from=build /opt/geoplatform-web .
COPY . .

ENV NODE_ENV=production \
    SENTRY_DSN_FILE=sentry_dsn \
    SENTRY_RELEASE=${SOURCE_COMMIT}

RUN mkdir -p /opt/bin
COPY docker/scripts/entrypoint.sh /opt/bin/

EXPOSE 5000
ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["node", "server.js"]
