# 1/2 Create build image
FROM node:10-alpine AS build

RUN mkdir -p /opt/geoplatform-web
WORKDIR /opt/geoplatform-web

COPY package.json yarn.lock ./
RUN yarn --production --frozen-lockfile

# 2/2 Create production image
FROM node:10-alpine
ARG SOURCE_COMMIT=unknown

RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
      libcrypto1.1 \
      curl=7.63.0-r0  \
      && \
    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
      proj4-dev=5.0.1-r1 \
      gdal=2.4.0-r0

RUN mkdir -p /opt/geoplatform-web
WORKDIR /opt/geoplatform-web

COPY --from=build /opt/geoplatform-web .
COPY . .

ENV NODE_ENV=production \
    SENTRY_DSN_FILE=sentry_dsn \
    SENTRY_RELEASE=${SOURCE_COMMIT}

RUN mkdir -p /opt/bin
COPY docker/scripts/entrypoint.sh /opt/bin/

EXPOSE 5000
ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["node", "server.js"]
