# 1/2 Create build image
FROM geodatagouv/node-gdal:10 AS build

RUN mkdir -p /opt/geoplatform-web
WORKDIR /opt/geoplatform-web

COPY package.json yarn.lock ./
RUN yarn --production --frozen-lockfile

# 2/2 Create production image
FROM geodatagouv/node-gdal:10
ARG SOURCE_COMMIT=unknown

RUN mkdir -p /opt/geoplatform-web
WORKDIR /opt/geoplatform-web

COPY --from=build /opt/geoplatform-web .
COPY . .

ENV NODE_ENV=production \
    SENTRY_DSN_FILE=sentry_dsn \
    SENTRY_RELEASE=${SOURCE_COMMIT}

RUN mkdir -p /opt/bin
COPY docker/scripts/entrypoint.sh /opt/bin/

EXPOSE 5000
ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["node", "server.js"]
