# 1/2 Create build image
FROM node:8 AS build

RUN mkdir -p /opt/geoplatform-worker
WORKDIR /opt/geoplatform-worker

COPY package.json yarn.lock ./
RUN yarn --production

# 2/2 Create production image
FROM node:8-slim

RUN apt-get update -qq && \
    apt-get install -qq -y gdal-bin

RUN mkdir -p /opt/geoplatform-worker
WORKDIR /opt/geoplatform-worker

COPY --from=build /opt/geoplatform-worker .
COPY . .

ENV NODE_ENV=production

EXPOSE 5000
CMD ["node", "worker.js"]
